#!/bin/sh

# git config core.hooksPath .githooks

shopt -s nocasematch
msg_file=$1
msg=$(cat "$msg_file")

declare -A regex_sections=(
  ["✨"]="^(✨|新增|feat)(\\(.+\\))?([ ]|[:：][ ]?)"
  ["🛠️"]="^(🛠️|修复|fix)(\\(.+\\))?([ ]|[:：][ ]?)"
  ["📚"]="^(📚|文档|docs)(\\(.+\\))?([ ]|[:：][ ]?)"
  ["🎨"]="^(🎨|风格|style)(\\(.+\\))?([ ]|[:：][ ]?)"
  ["🚀"]="^(🚀|性能|perf)(\\(.+\\))?([ ]|[:：][ ]?)"
  ["⚙️"]="^(⚙️|配置|config)(\\(.+\\))?([ ]|[:：][ ]?)"
  ["🌏"]="^(🌏|语言|i18n)(\\(.+\\))?([ ]|[:：][ ]?)"
  ["♻️"]="^(♻️|杂项|chore)(\\(.+\\))?([ ]|[:：][ ]?)"
)


for category in "${!regex_sections[@]}"; do
  regex=${regex_sections[$category]}
  if [[ $msg =~ $regex ]]; then
    clean_msg=$(echo "$msg" | sed -E "s/$regex/ /I")
    echo "$category $clean_msg" > "$msg_file"
    exit 0
  fi
done